openapi: 3.1.0
info:
  title: OpenApi specification - Replicator Service
  contact:
    name: Jules Trolet
    url: https://trolet.ca/pages/faq-contact
    email: engineering@trolet.ca
  version: "1.0"
servers:
- url: https://replicator-service-793462686782.us-central1.run.app
security:
- BearerAuth: []
paths:
  /rotate-key:
    post:
      tags:
      - token-controller
      summary: "Rotates token value, to be called every month on the first."
      operationId: createProduct
      responses:
        "200":
          description: Key rotated successfully
          content:
            application/hal+json:
              schema:
                type: object
  /product/update:
    post:
      tags:
      - product-controller
      summary: Update an existing Shopify product
      operationId: updateProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductBuilder"
        required: true
      responses:
        "200":
          description: Product updated successfully
          content:
            application/hal+json:
              schema:
                type: string
      security:
      - BearerAuth: []
  /product/create:
    post:
      tags:
      - product-controller
      summary: Create a new Shopify product
      operationId: createProduct_1
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductBuilder"
        required: true
      responses:
        "200":
          description: Product created successfully
          content:
            application/hal+json:
              schema:
                type: string
      security:
      - BearerAuth: []
  /testfetch:
    get:
      tags:
      - test-controller
      operationId: testFetch
      responses:
        "200":
          description: OK
          content:
            application/hal+json:
              schema:
                type: object
      security:
      - BearerAuth: []
  /testcreate:
    get:
      tags:
      - test-controller
      operationId: testCreate
      responses:
        "200":
          description: OK
          content:
            application/hal+json:
              schema:
                type: object
      security:
      - BearerAuth: []
  /test:
    get:
      tags:
      - test-controller
      operationId: test
      responses:
        "200":
          description: OK
          content:
            application/hal+json:
              schema:
                type: string
      security:
      - BearerAuth: []
components:
  schemas:
    ProductBuilder:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        type:
          type: string
        category:
          type: string
        handle:
          type: string
        tags:
          type: array
          items:
            type: string
        status:
          type: string
        color:
          type: string
        colorMetaobject:
          type: string
        size:
          type: string
        sizeMetaobject:
          type: string
        footwearMaterialMetaobject:
          type: string
        genderMetaobject:
          type: string
        descriptionHtml:
          type: string
        descriptionMetafield:
          type: string
        definitionEtat:
          type: string
        condition:
          type: string
        dimensions:
          type: string
        medias:
          type: array
          items:
            type: string
        price:
          type: string
        compareAtPrice:
          type: string
        sku:
          type: string
        location:
          type: string
  securitySchemes:
    BearerAuth:
      type: http
      in: header
      scheme: bearer
      bearerFormat: JWT
