# .github/workflows/regenerate-ts-axios-client.yml
name: Regenerate TypeScript-Axios Client

on:
  # every 20 minutes
  schedule:
    - cron: '*/3 * * * *'           
  workflow_dispatch: {}             
jobs:
  generate-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
    
      # 1. Fetch the OpenAPI spec
      - name: Download OpenAPI spec
        run: |
          curl -sSL "${{ secrets.SPEC_URL }}" -o spec.yaml

      # 2. Install OpenAPI Generator CLI
      - name: Install OpenAPI Generator CLI
        run: |
          npm install @openapitools/openapi-generator-cli -g

      # 3. Generate the TS-Axios client
      - name: Generate TS-Axios client
        run: |
          openapi-generator-cli generate \
            -i spec.yaml \
            -g typescript-axios \
            -o generated-client

      # 5. Replace with newly generated code
      - name: Sync generated code
        run: |
          rm -rf client-repo/*
          cp -R generated-client/* client-repo/

      # 6. Commit & push back to client repo
      - name: Commit and push changes
        run: |
          cd client-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git add .
            git commit -m "chore: regenerate TS-Axios client"
            git push
          fi
