name: Regenerate TypeScript-Axios Client

on:
  schedule:
    - cron: '*/3 * * * *'
  workflow_dispatch:

permissions:
  contents: write  # allows reading/writing repo contents with GITHUB_TOKEN

jobs:
  generate-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout this repo (with token to push later)
      - name: Checkout origin repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # leave GITHUB_TOKEN in git config
          fetch-depth: 0            # full history to avoid detached HEAD

      # 2. Download the live OpenAPI spec
      - name: Download OpenAPI spec
        run: |
          curl -sSL "${{ secrets.SPEC_URL }}" -o spec.yaml

      # 3. Patch the invalid scheme name (no spaces allowed) :contentReference[oaicite:2]{index=2}
      - name: Rename security scheme for validation
        run: |
          sed -i 's/Bearer Authentication/BearerAuth/g' spec.yaml

      # 4. (Optional) Show a base64‐encoded snippet to inspect without redaction :contentReference[oaicite:3]{index=3}
      - name: Preview spec (base64)
        run: |
          head -n 20 spec.yaml | base64

      # 5. Install the OpenAPI Generator CLI
      - name: Install OpenAPI Generator CLI
        run: |
          npm install @openapitools/openapi-generator-cli -g

      # 6. Generate the TypeScript-Axios client (skip validation if anything else fails) :contentReference[oaicite:4]{index=4}
      - name: Generate TS-Axios client
        run: |
          openapi-generator-cli generate \
            -i spec.yaml \
            -g typescript-axios \
            -o generated-client \
            --skip-validate-spec

      # 7. Checkout the dedicated client repo to push into it
      - name: Checkout client repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      # 8. Sync over generated code and commit if changed
      - name: Sync generated client & push
        run: |
          rm -rf client-repo/*
          cp -R generated-client/* client-repo/
          cd client-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git diff --quiet; then
            echo "✅ No changes to commit"
          else
            git add .
            git commit -m "chore: regenerate TS-Axios client"
            git push
          fi
